version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build --prod
  post_build:
    commands:
      - echo Build completed on `date`
      - cd dist/gwt-app && zip -r ../../dist.zip .
artifacts:
  files:
    - 'dist.zip'
  name: dist
